import Head from "next/head";
import FrButton from "../../components/FrButton";
import { FrCardCategory, FrCardGroup } from "../../components/FrCard";

export default function Components() {
  return (
    <div className="min-h-screen w-full">
      <img className="fixed top-0 right-0 -z-10" src="/images/bg_1.svg"></img>
      <img className="fixed bottom-0 left-0 -z-10" src="/images/bg_2.svg"></img>
      <img
        className="fixed top-0 left-0 mt-10 ml-14 -z-10"
        src="/icons/fr_icon.svg"
      ></img>
      <div className="container mt-44 bg-transparent mx-auto">
        <Head>
          <title>RunRide</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>
          <div className="flex space-x-4">
            <div className="form-control w-full max-w-xs">
              <label className="label">
                <span className="fr-text-caption text-black">
                  Default Field
                </span>
              </label>
              <input
                type="text"
                placeholder="Type here"
                className="input input-bordered w-full max-w-xs fr-text-body placeholder-darkgrey border-lightgrey rounded-[5px]"
              />
            </div>
            <div className="form-control w-full max-w-xs">
              <label className="label">
                <span className="fr-text-caption text-black">
                  Calendar Picker
                </span>
              </label>
              <div className="flex items-center relative">
                <input
                  type="date"
                  placeholder="Pilih Tanggal Lahir"
                  className="input input-bordered w-full max-w-xs fr-text-body placeholder-darkgret border-lightgrey rounded-[5px]"
                  required
                />
                <img
                  className="absolute mr-[1.1rem] right-0"
                  src="/icons/ic_calendar.svg"
                />
              </div>
            </div>
            {/* <div className="form-control w-full max-w-xs">
              <label className="label">
                <span className="fr-text-caption text-black">Dropdown</span>
              </label>
              <div className="flex items-center relative">
                <select
                  required
                  className="select select-bordered w-full max-w-xs fr-text-body placeholder-darkgrey border-lightgrey rounded-[5px] font-medium"
                >
                  <option value="" disabled selected>
                    Pick category
                  </option>
                  <option>T-shirts</option>
                  <option>Mugs</option>
                </select>
              </div>
            </div> */}
          </div>
          <div className="flex space-x-4 mt-5">
            <FrButton label="Primary" color="primary" />
            <FrButton label="Secondary" color="secondary" />
            <FrButton color="accent" icon="/icons/ic_circle_done_white.svg" />
          </div>
          <FrCardCategory
            title={"01.A"}
            category={"RUN"}
            rules={[
              "Tim",
              "Komponen Tim (5 Anggota dengan 3 Pria dan 2 Wanita)",
              "Usia ≤ 40 Tahun",
              "Total Jarak 77 km per-tim",
            ]}
            onClickAction={() => {
              console.log("Click Card Category");
            }}
          />
          <FrCardGroup
            title={"01.A"}
            category={"RUN"}
            captainName={"Fikr Lazuardi Islah"}
            onClickAction={() => {
              console.log("Click Card Group");
            }}
          />
        </main>
      </div>
    </div>
  );
}
